### ISSUE TITLE
NetOffice: Future Instances of Re-Occurring Appointment Not Being Created

### ISSUE THREAD

**Issue by JaySmith-zz** [JaySmith/Marble#11]
Similar issue with NetOffice Library that @DanielJGoodwin is working on.

**Comment by DanielJGoodwin** [comment]
I have filed an issue with NetOffice to fix recurrences to work correctly. Office.Interop will add all future recurrences to the list of appointments by enabling "IncludeRecurrences". NetOffice has the same feature, however, it's not working.  

Here is the issue log to read more: https://netoffice.codeplex.com/workitem/21697

**Comment by JaySmith-zz** [comment]
Any chance we could fix it ourselves?  NetOffice is open source.

Jay
